### ISSUE TITLE
Nuget package for Metrics.NET.Serilog

### ISSUE THREAD

**Issue by tjrobinson** [alexmg/Metrics.NET.Serilog#1]
Alex,

I've come across this project and would like to use it but there's currently no nuget package on nuget.org so I'm referencing the dll directly. I can see that you've created a `.nuspec` file but was wondering if you have any plans to publish it to nuget.org? I would be happy to help if I can.

Thanks,

Tom

**Comment by alexmg** [comment]
I decided to move from Metrics.NET to AppMetrics and created [AppMetricsSerilogReporter](https://github.com/alexmg/AppMetricsSerilogReporter) which is a similar project.
